/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.construtora.viewVenda;

import br.com.construtora.controller.AdmController;
import br.com.construtora.controller.ClienteController;
import br.com.construtora.controller.ContratoController;
import br.com.construtora.controller.ImovelController;
import br.com.construtora.model.Administrador;
import br.com.construtora.model.Cliente;
import br.com.construtora.model.Contrato;
import br.com.construtora.model.Imovel;
import br.com.construtora.util.MensagemUtilAdm;
import br.com.construtora.util.MensagemUtilCliente;
import br.com.construtora.util.MensagemUtilContrato;
import br.com.construtora.util.MensagemUtilImovel;
import br.com.construtora.util.MensagemUtilUsuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe Lacerda
 */
public class CadastrarVenda extends javax.swing.JDialog {

    Cliente cliente = new Cliente();
    ClienteController cliControl = new ClienteController();

    Administrador admin = new Administrador();
    AdmController admControl = new AdmController();

    Imovel imovel = new Imovel();
    ImovelController imoControl = new ImovelController();

    Contrato contrato = new Contrato();
    ContratoController contControl = new ContratoController();

    /**
     * Creates new form CadastrarVenda
     */
    public CadastrarVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbimovel = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbcli = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbadm = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfsenhaimo = new javax.swing.JTextField();
        jbproimo = new javax.swing.JButton();
        tfsenhacli = new javax.swing.JTextField();
        tfsenhaadm = new javax.swing.JTextField();
        jbprocli = new javax.swing.JButton();
        jbproadm = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbcertimo = new javax.swing.JComboBox();
        cbcertcli = new javax.swing.JComboBox();
        cbcertadm = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SD Construtora - Cadastrar");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(810, 635));
        getContentPane().setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CADASTRAR VENDA");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(330, 10, 220, 17);

        tbimovel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Imóvel:", "Tamanho:", "Preço:", "Andamento:", "Cidade:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbimovel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 450, 460, 50);

        tbcli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cliente:", "Nome:", "CPF:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbcli);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(0, 140, 460, 50);

        tbadm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Adm:", "Nome:", "CPF:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbadm);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 290, 460, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Dados do Cliente:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 80, 160, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Dados do Vendedor:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 230, 160, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Dados do Imóvel:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 380, 160, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Informe a SENHA:  ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 430, 220, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Certificação do Imóvel:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(490, 480, 220, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Informe a SENHA:  ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 270, 220, 14);
        getContentPane().add(tfsenhaimo);
        tfsenhaimo.setBounds(310, 420, 110, 30);

        jbproimo.setBackground(new java.awt.Color(255, 255, 255));
        jbproimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pro.png"))); // NOI18N
        jbproimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbproimoActionPerformed(evt);
            }
        });
        getContentPane().add(jbproimo);
        jbproimo.setBounds(420, 420, 40, 30);
        getContentPane().add(tfsenhacli);
        tfsenhacli.setBounds(310, 110, 110, 30);
        getContentPane().add(tfsenhaadm);
        tfsenhaadm.setBounds(310, 260, 110, 30);

        jbprocli.setBackground(new java.awt.Color(255, 255, 255));
        jbprocli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pro.png"))); // NOI18N
        jbprocli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbprocliActionPerformed(evt);
            }
        });
        getContentPane().add(jbprocli);
        jbprocli.setBounds(420, 110, 40, 30);

        jbproadm.setBackground(new java.awt.Color(255, 255, 255));
        jbproadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pro.png"))); // NOI18N
        jbproadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbproadmActionPerformed(evt);
            }
        });
        getContentPane().add(jbproadm);
        jbproadm.setBounds(420, 260, 40, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Informe a SENHA:  ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 120, 220, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Certificação do Cliente:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(490, 170, 220, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Certificação do Adm:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(490, 320, 220, 14);

        cbcertimo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "Aprovado", "Em Espera", "Recusado" }));
        getContentPane().add(cbcertimo);
        cbcertimo.setBounds(650, 470, 130, 30);

        cbcertcli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "Aprovado", "Em Espera", "Recusado" }));
        getContentPane().add(cbcertcli);
        cbcertcli.setBounds(650, 160, 130, 30);

        cbcertadm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "Aprovado", "Em Espera", "Recusado" }));
        getContentPane().add(cbcertadm);
        cbcertadm.setBounds(650, 310, 130, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/V.gif"))); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 530, 130, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/X.gif"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 530, 130, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cad.jpg"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbproimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbproimoActionPerformed
        String senha = (String) tfsenhaimo.getText();
        try {
            imovel = imoControl.procurarImovelSenha(senha);
        } catch (Exception ex) {
            Logger.getLogger(CadastrarVenda.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, MensagemUtilImovel.getValor(MensagemUtilImovel.MSG_ERRO_PROCURARIMO), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO), JOptionPane.ERROR_MESSAGE);
        }
        if (imovel.getIdImovel().equals(senha)) {
            String[] colunas = {"ID Imóvel: ", "Tamanho: ", "Preço: ", "Andamento: ", "Cidade: "};
            Object[][] dados = {
                {imovel.getIdImovel(), imovel.getTamanho(), imovel.getPreco(), imovel.getAndamentoObra(), imovel.getEnderecoImovel().getCidade()}
            };
            tbimovel.setModel(new DefaultTableModel(dados, colunas));

        } else {
            JOptionPane.showMessageDialog(null, MensagemUtilImovel.getValor(MensagemUtilImovel.MSG_ERRO_PROCURARIMO), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO), JOptionPane.ERROR_MESSAGE);
        }
        contrato.setImovel(imovel);
    }//GEN-LAST:event_jbproimoActionPerformed

    private void jbprocliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbprocliActionPerformed
        String senha = (String) tfsenhacli.getText();
        try {
            cliente = cliControl.procurarCliente(senha);
        } catch (Exception ex) {
            Logger.getLogger(CadastrarVenda.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, MensagemUtilCliente.getValor(MensagemUtilCliente.MSG_ERRO_PROCURARCLI), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO), JOptionPane.ERROR_MESSAGE);
        }
        if (cliente.getUsuarioCli().getSenha().equals(senha)) {
            String[] colunas = {"ID Cliente: ", "Nome: ", "CPF: "};
            Object[][] dados = {
                {cliente.getIdCli(), cliente.getNomeCli(), cliente.getCpfCli()}
            };
            tbcli.setModel(new DefaultTableModel(dados, colunas));

        } else {
            JOptionPane.showMessageDialog(null, MensagemUtilCliente.getValor(MensagemUtilCliente.MSG_ERRO_PROCURARCLI), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO), JOptionPane.ERROR_MESSAGE);
        }
        contrato.setCliente(cliente);
    }//GEN-LAST:event_jbprocliActionPerformed

    private void jbproadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbproadmActionPerformed
        String senha = (String) tfsenhaadm.getText();
        try {
            admin = admControl.procurarAdm(senha);
        } catch (Exception ex) {
            Logger.getLogger(CadastrarVenda.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, MensagemUtilCliente.getValor(MensagemUtilCliente.MSG_ERRO_PROCURARCLI), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO), JOptionPane.ERROR_MESSAGE);
        }
        if (admin.getUsuarioAdm().getSenha().equals(senha)) {
            String[] colunas = {"ID Adm: ", "Nome: ", "CPF: "};
            Object[][] dados = {
                {admin.getIdAdm(), admin.getNomeAdm(), admin.getCpfAdm()}
            };
            tbadm.setModel(new DefaultTableModel(dados, colunas));

        } else {
            JOptionPane.showMessageDialog(null, MensagemUtilAdm.getValor(MensagemUtilAdm.MSG_ERRO_PROCURARADM), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO), JOptionPane.ERROR_MESSAGE);
        }
        contrato.setAdmin(admin);
    }//GEN-LAST:event_jbproadmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        contrato.setCertificacaoCli((String) cbcertcli.getSelectedItem());
        contrato.setCertificacaoAdm((String) cbcertadm.getSelectedItem());
        contrato.setCertificacaoImo((String) cbcertimo.getSelectedItem());

        try {
            int resp = JOptionPane.showConfirmDialog(null, MensagemUtilUsuario.getValor(MensagemUtilUsuario.MSG_CAD), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_CAD), JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                contControl.salvarContrato(contrato);
                JOptionPane.showMessageDialog(null, MensagemUtilContrato.getValor(MensagemUtilContrato.MSG_SUCESSO_SALVARCONT));
                dispose();
            }
        } catch (Exception ex) {
            Logger.getLogger(CadastrarVenda.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, MensagemUtilContrato.getValor(MensagemUtilContrato.MSG_ERRO_SALVARCONT), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, MensagemUtilUsuario.getValor(MensagemUtilUsuario.MSG_CANCEL), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_SAIR), JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarVenda dialog = new CadastrarVenda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbcertadm;
    private javax.swing.JComboBox cbcertcli;
    private javax.swing.JComboBox cbcertimo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbproadm;
    private javax.swing.JButton jbprocli;
    private javax.swing.JButton jbproimo;
    private javax.swing.JTable tbadm;
    private javax.swing.JTable tbcli;
    private javax.swing.JTable tbimovel;
    private javax.swing.JTextField tfsenhaadm;
    private javax.swing.JTextField tfsenhacli;
    private javax.swing.JTextField tfsenhaimo;
    // End of variables declaration//GEN-END:variables
}
