/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.construtora.view;

import br.com.construtora.controller.AdmController;
import br.com.construtora.controller.ClienteController;
import br.com.construtora.model.Administrador;
import br.com.construtora.model.Cliente;
import br.com.construtora.model.Contato;
import br.com.construtora.model.Endereco;
import br.com.construtora.model.Usuario;
import br.com.construtora.util.DateUtil;
import br.com.construtora.util.MensagemUtilAdm;
import br.com.construtora.util.MensagemUtilCliente;
import br.com.construtora.util.MensagemUtilUsuario;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Lacerda
 */
public class Atualizar extends javax.swing.JDialog {

    Administrador adm = new Administrador();
    AdmController admControl = new AdmController();
    Cliente cliente = new Cliente();
    ClienteController clienteControl = new ClienteController();

    /**
     * Creates new form AtualizarAdm
     */
    public Atualizar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pfsenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jbprocurar = new javax.swing.JButton();
        cbselecione = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbatualizardados = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jblimpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfnome = new javax.swing.JTextField();
        tfcpf = new javax.swing.JFormattedTextField();
        tfdata = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tfcep = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        tfuf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfnumero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbcidade = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfrua = new javax.swing.JTextField();
        tfbairro = new javax.swing.JTextField();
        spcomplemento = new javax.swing.JScrollPane();
        tacomplemento = new javax.swing.JTextArea();
        tfcelular = new javax.swing.JFormattedTextField();
        tfemail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tflogin = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfsenha = new javax.swing.JTextField();
        tfantcidade = new javax.swing.JTextField();
        jlidende = new javax.swing.JLabel();
        jlidcont = new javax.swing.JLabel();
        jlid = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SD Construtora - Atualizar");
        setMaximumSize(new java.awt.Dimension(810, 635));
        setMinimumSize(new java.awt.Dimension(810, 635));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(810, 635));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ATUALIZAR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 10, 110, 15);
        getContentPane().add(pfsenha);
        pfsenha.setBounds(200, 70, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Informe a senha/id:  ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 220, 14);

        jbprocurar.setBackground(new java.awt.Color(255, 255, 255));
        jbprocurar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felipe Lacerda\\Downloads\\SD Azul\\pro.png")); // NOI18N
        jbprocurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbprocurarActionPerformed(evt);
            }
        });
        getContentPane().add(jbprocurar);
        jbprocurar.setBounds(440, 70, 40, 30);

        cbselecione.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbselecione.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "Cliente", "Administrador", "Imóvel" }));
        cbselecione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbselecioneActionPerformed(evt);
            }
        });
        getContentPane().add(cbselecione);
        cbselecione.setBounds(320, 70, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Dados: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 110, 90, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Contato: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 390, 100, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Endereço: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 250, 110, 15);

        jbatualizardados.setBackground(new java.awt.Color(255, 255, 255));
        jbatualizardados.setForeground(new java.awt.Color(0, 255, 0));
        jbatualizardados.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felipe Lacerda\\Downloads\\SD Azul\\up.png")); // NOI18N
        jbatualizardados.setText("Atualizar");
        jbatualizardados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbatualizardadosActionPerformed(evt);
            }
        });
        getContentPane().add(jbatualizardados);
        jbatualizardados.setBounds(560, 530, 110, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felipe Lacerda\\Downloads\\SD Azul\\fe.png")); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 530, 110, 40);

        jblimpar.setBackground(new java.awt.Color(255, 255, 255));
        jblimpar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felipe Lacerda\\Downloads\\SD Azul\\lix.png")); // NOI18N
        jblimpar.setText("Limpar Campos");
        jblimpar.setActionCommand("  Limpar Campos");
        jblimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblimparActionPerformed(evt);
            }
        });
        getContentPane().add(jblimpar);
        jblimpar.setBounds(480, 70, 150, 30);

        jLabel7.setText("Nome: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 140, 100, 14);

        tfnome.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(tfnome);
        tfnome.setBounds(100, 130, 180, 30);

        tfcpf.setForeground(new java.awt.Color(255, 0, 0));
        try {
            tfcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfcpf);
        tfcpf.setBounds(100, 170, 110, 30);

        tfdata.setForeground(new java.awt.Color(255, 0, 0));
        try {
            tfdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfdata);
        tfdata.setBounds(420, 170, 80, 30);

        jLabel6.setText("Data de Nascimento: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 180, 170, 14);

        tfcep.setForeground(new java.awt.Color(255, 0, 0));
        try {
            tfcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfcep);
        tfcep.setBounds(100, 270, 80, 30);

        jLabel10.setText("UF:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 360, 60, 14);

        tfuf.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(tfuf);
        tfuf.setBounds(370, 350, 30, 30);

        jLabel11.setText("Nº:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 360, 40, 14);

        tfnumero.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(tfnumero);
        tfnumero.setBounds(470, 350, 30, 30);

        jLabel12.setText("Cidade ATUAL: ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(270, 280, 100, 14);

        jLabel13.setText("NOVA Cidade:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(270, 320, 100, 14);

        cbcidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "Pombal", "São Bentinho", "Cajazeirinhas", "São Domingos" }));
        getContentPane().add(cbcidade);
        cbcidade.setBounds(370, 310, 130, 30);

        jLabel14.setText("Rua: ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 320, 70, 14);

        jLabel15.setText("Bairro: ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(560, 280, 80, 14);

        jLabel16.setText("Complemento: ");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(520, 320, 120, 14);

        jLabel18.setText("E-mail: ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(40, 460, 90, 14);

        tfrua.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(tfrua);
        tfrua.setBounds(100, 310, 150, 30);

        tfbairro.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(tfbairro);
        tfbairro.setBounds(620, 270, 150, 30);

        tacomplemento.setColumns(20);
        tacomplemento.setForeground(new java.awt.Color(255, 0, 0));
        tacomplemento.setRows(5);
        spcomplemento.setViewportView(tacomplemento);

        getContentPane().add(spcomplemento);
        spcomplemento.setBounds(620, 310, 150, 80);

        tfcelular.setForeground(new java.awt.Color(255, 0, 0));
        try {
            tfcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfcelular);
        tfcelular.setBounds(110, 410, 140, 30);

        tfemail.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(tfemail);
        tfemail.setBounds(110, 450, 190, 30);

        jLabel20.setText("CPF: ");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(50, 180, 80, 14);

        jLabel21.setText("Celular:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(40, 420, 130, 14);

        jLabel22.setText("CEP:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(40, 280, 140, 14);

        jLabel24.setText("Login: ");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(370, 140, 70, 20);

        tflogin.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(tflogin);
        tflogin.setBounds(420, 130, 110, 30);

        jLabel25.setText("Senha: ");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(560, 140, 80, 14);

        tfsenha.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(tfsenha);
        tfsenha.setBounds(620, 130, 120, 30);

        tfantcidade.setEditable(false);
        tfantcidade.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(tfantcidade);
        tfantcidade.setBounds(370, 270, 130, 30);

        jlidende.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jlidende);
        jlidende.setBounds(110, 240, 110, 30);

        jlidcont.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jlidcont);
        jlidcont.setBounds(100, 380, 110, 30);

        jlid.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jlid);
        jlid.setBounds(100, 100, 80, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felipe Lacerda\\Downloads\\SD Azul\\cad.jpg")); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbprocurarActionPerformed
        String resp = (String) cbselecione.getSelectedItem();
        String senha = new String(this.pfsenha.getPassword());

        if (resp.equals("Cliente")) {
            try {
                cliente = clienteControl.procurarCliente(senha);
            } catch (Exception ex) {
                Logger.getLogger(Atualizar.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,MensagemUtilCliente.getValor(MensagemUtilCliente.MSG_ERRO_PROCURARCLI), "ERRO ao procurar o Cliente!", JOptionPane.ERROR_MESSAGE);
            }
            if (cliente.getUsuarioCli().getSenha().equals(senha)) {
                String idCli = String.valueOf(cliente.getIdCli());
                jlid.setText(idCli);

                String idCont = String.valueOf(cliente.getContatoCli().getId());
                jlidcont.setText(idCont);

                String idEnde = String.valueOf(cliente.getEnderecoCli().getId());
                jlidende.setText(idEnde);

                tflogin.setText(cliente.getUsuarioCli().getLogin());
                tfsenha.setText(cliente.getUsuarioCli().getSenha());

                tfnome.setText(cliente.getNomeCli());
                tfcpf.setText(cliente.getCpfCli());

                DateUtil dataNas = new DateUtil();
                String data = dataNas.dateToString(cliente.getDataNascimento());
                tfdata.setText(data);

                tfcep.setText(cliente.getEnderecoCli().getCep());
                tfantcidade.setText(cliente.getEnderecoCli().getCidade());
                tfrua.setText(cliente.getEnderecoCli().getRua());
                tfbairro.setText(cliente.getEnderecoCli().getBairro());
                tfuf.setText(cliente.getEnderecoCli().getUf());
                tfnumero.setText(cliente.getEnderecoCli().getNumero());
                tacomplemento.setText(cliente.getEnderecoCli().getComplemento());

                tfcelular.setText(cliente.getContatoCli().getCelular());
                tfemail.setText(cliente.getContatoCli().getEmail());
            } else {
                JOptionPane.showMessageDialog(null, MensagemUtilCliente.getValor(MensagemUtilCliente.MSG_ERRO_PROCURARCLI), "ERRO ao procurar o Cliente!", JOptionPane.ERROR_MESSAGE);
            }
        } else if (resp.equals("Administrador")) {
            try {
                adm = admControl.procurarAdm(senha);
            } catch (Exception ex) {
                Logger.getLogger(Atualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (adm.getUsuarioAdm().getSenha().equals(senha)) {
                String idAdm = String.valueOf(adm.getIdAdm());
                jlid.setText(idAdm);

                String idCont = String.valueOf(adm.getContatoAdm().getId());
                jlidcont.setText(idCont);

                String idEnde = String.valueOf(adm.getEnderecoAdm().getId());
                jlidende.setText(idEnde);

                tflogin.setText(adm.getUsuarioAdm().getLogin());
                tfsenha.setText(adm.getUsuarioAdm().getSenha());

                tfnome.setText(adm.getNomeAdm());
                tfcpf.setText(adm.getCpfAdm());

                /*DateUtil dataNas = new DateUtil();
                 String data = dataNas.dateToString(cliente.getDataNascimento());
                 jldata.setText(data);*/
                tfcep.setText(adm.getEnderecoAdm().getCep());
                tfantcidade.setText(adm.getEnderecoAdm().getCidade());
                tfrua.setText(adm.getEnderecoAdm().getRua());
                tfbairro.setText(adm.getEnderecoAdm().getBairro());
                tfuf.setText(adm.getEnderecoAdm().getUf());
                tfnumero.setText(adm.getEnderecoAdm().getNumero());
                tacomplemento.setText(adm.getEnderecoAdm().getComplemento());

                tfcelular.setText(adm.getContatoAdm().getCelular());
                tfemail.setText(adm.getContatoAdm().getEmail());
            } else {
                JOptionPane.showMessageDialog(null,MensagemUtilAdm.getValor(MensagemUtilAdm.MSG_ERRO_PROCURARADM),MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO), JOptionPane.ERROR_MESSAGE);
            }
        } /*else if (resp.equals("Imóvel")) {
         this.dispose();
         AtualizarImovel atualizarImo = new AtualizarImovel(null, true);
         atualizarImo.setVisible(true);
         }*/
    }//GEN-LAST:event_jbprocurarActionPerformed

    private void jbatualizardadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbatualizardadosActionPerformed
        Usuario usu = new Usuario();
        Endereco ende = new Endereco();
        Contato cont = new Contato();
        Administrador admin = new Administrador();

        String resp = (String) cbselecione.getSelectedItem();

        if (resp.equals("Cliente")) {
            
            Long idCli = Long.valueOf(jlid.getText());
            cliente.setIdCli(idCli);

            usu.setLogin(tflogin.getText());
            usu.setSenha(tfsenha.getText());
            cliente.setUsuarioCli(usu);

            cliente.setNomeCli(tfnome.getText());
            cliente.setCpfCli(tfcpf.getText());

            DateUtil datautil = new DateUtil();
            Date data = datautil.stringToDate(tfdata.getText());
            cliente.setDataNascimento(data);

            Long idEnde = Long.valueOf(jlidende.getText());
            ende.setId(idEnde);
            ende.setCep(tfcep.getText());
            ende.setUf(tfuf.getText());
            ende.setNumero(tfnumero.getText());
            if (!cbcidade.getSelectedItem().equals("SELECIONE")) {
                ende.setCidade((String) cbcidade.getSelectedItem());
            } else {
                ende.setCidade(tfantcidade.getText());
            }
            ende.setRua(tfrua.getText());
            ende.setBairro(tfbairro.getText());
            ende.setComplemento(tacomplemento.getText());
            cliente.setEnderecoCli(ende);

            Long idCont = Long.valueOf(jlidcont.getText());
            cont.setId(idCont);
            cont.setCelular(tfcelular.getText());
            cont.setEmail(tfemail.getText());
            cliente.setContatoCli(cont);

            try {
                clienteControl.atualizarCliente(cliente);
                JOptionPane.showMessageDialog(null,MensagemUtilCliente.getValor(MensagemUtilCliente.MSG_SUCESSO_EDITARCLI));
                dispose();
            } catch (Exception ex) {
                Logger.getLogger(Atualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (resp.equals("Administrador")) {
            
             Long idAdm = Long.valueOf(jlid.getText());
            admin.setIdAdm(idAdm);

            usu.setLogin(tflogin.getText());
            usu.setSenha(tfsenha.getText());
            admin.setUsuarioAdm(usu);

            admin.setNomeAdm(tfnome.getText());
            admin.setCpfAdm(tfcpf.getText());

            /*DateUtil datautil = new DateUtil();
            Date data = datautil.stringToDate(tfdata.getText());
            admin.setDataNascimento(data);*/

            Long idEnde = Long.valueOf(jlidende.getText());
            ende.setId(idEnde);
            ende.setCep(tfcep.getText());
            ende.setUf(tfuf.getText());
            ende.setNumero(tfnumero.getText());
            if (!cbcidade.getSelectedItem().equals("SELECIONE")) {
                ende.setCidade((String) cbcidade.getSelectedItem());
            } else {
                ende.setCidade(tfantcidade.getText());
            }
            ende.setRua(tfrua.getText());
            ende.setBairro(tfbairro.getText());
            ende.setComplemento(tacomplemento.getText());
            admin.setEnderecoAdm(ende);

            Long idCont = Long.valueOf(jlidcont.getText());
            cont.setId(idCont);
            cont.setCelular(tfcelular.getText());
            cont.setEmail(tfemail.getText());
            admin.setContatoAdm(cont);

            try {
                admControl.atualizarAdm(admin);
                JOptionPane.showMessageDialog(null,MensagemUtilAdm.getValor(MensagemUtilAdm.MSG_SUCESSO_EDITARADM));
                dispose();
            } catch (Exception ex) {
                Logger.getLogger(Atualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jbatualizardadosActionPerformed

    private void cbselecioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbselecioneActionPerformed
        String resp = (String) cbselecione.getSelectedItem();

        if (resp.equals("Imóvel")) {
            this.dispose();
            AtualizarImovel atualizarImo = new AtualizarImovel(null, true);
            atualizarImo.setVisible(true);
        }else if(resp.equals("Administrador")) {
            tfdata.setEditable(false);
        }
    }//GEN-LAST:event_cbselecioneActionPerformed

    private void jblimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblimparActionPerformed
        jlid.setText("");
        jlidcont.setText("");
        jlidende.setText("");

        pfsenha.setText("");
        cbselecione.setSelectedItem("SELECIONE");

        tflogin.setText("");
        tfsenha.setText("");

        tfnome.setText("");
        tfcpf.setText("");
        tfdata.setText("");

        tfcep.setText("");
        tfantcidade.setText("");
        cbcidade.setSelectedItem("SELECIONE");
        tfrua.setText("");
        tfbairro.setText("");
        tfuf.setText("");
        tfnumero.setText("");
        tacomplemento.setText("");

        tfcelular.setText("");
        tfemail.setText("");
    }//GEN-LAST:event_jblimparActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, MensagemUtilUsuario.getValor(MensagemUtilUsuario.MSG_CANCEL),MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_CANCEL), JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Atualizar dialog = new Atualizar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbcidade;
    private javax.swing.JComboBox cbselecione;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbatualizardados;
    private javax.swing.JButton jblimpar;
    private javax.swing.JButton jbprocurar;
    private javax.swing.JLabel jlid;
    private javax.swing.JLabel jlidcont;
    private javax.swing.JLabel jlidende;
    private javax.swing.JPasswordField pfsenha;
    private javax.swing.JScrollPane spcomplemento;
    private javax.swing.JTextArea tacomplemento;
    private javax.swing.JTextField tfantcidade;
    private javax.swing.JTextField tfbairro;
    private javax.swing.JFormattedTextField tfcelular;
    private javax.swing.JFormattedTextField tfcep;
    private javax.swing.JFormattedTextField tfcpf;
    private javax.swing.JFormattedTextField tfdata;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tflogin;
    private javax.swing.JTextField tfnome;
    private javax.swing.JTextField tfnumero;
    private javax.swing.JTextField tfrua;
    private javax.swing.JTextField tfsenha;
    private javax.swing.JTextField tfuf;
    // End of variables declaration//GEN-END:variables
}
