/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.construtora.view;

import br.com.construtora.controller.AdmController;
import br.com.construtora.controller.ClienteController;
import br.com.construtora.model.Administrador;
import br.com.construtora.model.Cliente;
import br.com.construtora.util.MensagemUtilUsuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Lacerda
 */
public class Login extends javax.swing.JDialog {

    private ClienteController clienteControl = new ClienteController();
    private AdmController admControl = new AdmController();
    Cliente cliente = new Cliente();
    Administrador adm = new Administrador();

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbselecione = new javax.swing.JComboBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        jllogin = new javax.swing.JLabel();
        tflogin = new javax.swing.JTextField();
        jlsenha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pfsenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SD Construtora - Login Usuário");
        setIconImage(null);
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(450, 420));
        setMinimumSize(new java.awt.Dimension(450, 420));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(460, 460));
        getContentPane().setLayout(null);

        cbselecione.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbselecione.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "Cliente", "Administrador" }));
        cbselecione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbselecioneActionPerformed(evt);
            }
        });
        getContentPane().add(cbselecione);
        cbselecione.setBounds(160, 280, 170, 30);

        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felipe Lacerda\\Downloads\\SD Azul\\adc2.png")); // NOI18N
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(160, 70, 110, 110);

        jllogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jllogin.setForeground(new java.awt.Color(255, 255, 255));
        jllogin.setText("Login: ");
        getContentPane().add(jllogin);
        jllogin.setBounds(100, 200, 80, 17);
        getContentPane().add(tflogin);
        tflogin.setBounds(160, 200, 170, 30);

        jlsenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlsenha.setForeground(new java.awt.Color(255, 255, 255));
        jlsenha.setText("Senha: ");
        getContentPane().add(jlsenha);
        jlsenha.setBounds(100, 240, 80, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felipe Lacerda\\Downloads\\SD Azul\\cadi.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 230, 30, 40);
        getContentPane().add(pfsenha);
        pfsenha.setBounds(160, 240, 170, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felipe Lacerda\\Downloads\\SD Azul\\seta.png")); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 370, 140, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felipe Lacerda\\Downloads\\SD Azul\\fecbola.gif")); // NOI18N
        jButton2.setText(" Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 370, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGIN USUÁRIO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 10, 130, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felipe Lacerda\\Downloads\\SD Azul\\login.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 450, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbselecioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbselecioneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbselecioneActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null,MensagemUtilUsuario.getValor(MensagemUtilUsuario.MSG_SAIR),MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_SAIR), JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String resp = (String) cbselecione.getSelectedItem();
        String senha = new String(this.pfsenha.getPassword());

        Cliente clienteRetorno = null;
        Administrador admRetorno = null;

        if (tflogin.getText().equals("")) {
            jllogin.setForeground(new java.awt.Color(255, 0, 0));
            JOptionPane.showMessageDialog(null,MensagemUtilUsuario.getValor(MensagemUtilUsuario.MSG_OBG),MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_OBG), JOptionPane.ERROR_MESSAGE);
        } else if (pfsenha.getText().equals("")) {
            jlsenha.setForeground(new java.awt.Color(255, 0, 0));
            JOptionPane.showMessageDialog(null,MensagemUtilUsuario.getValor(MensagemUtilUsuario.MSG_OBG),MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_OBG), JOptionPane.ERROR_MESSAGE);
        } else {
            if (resp.equals("Cliente")) {
                try {
                    clienteRetorno = clienteControl.procurarCliente(senha);
                    if (clienteRetorno == null) {
                        JOptionPane.showMessageDialog(null,MensagemUtilUsuario.getValor(MensagemUtilUsuario.MSG_CAMPO_CERTO),MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO), JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (clienteRetorno.getUsuarioCli().getSenha().equals(senha)) {
                    MenuCliente menuCli = new MenuCliente();
                    String login = clienteRetorno.getUsuarioCli().getLogin();
                    String nome = clienteRetorno.getNomeCli();
                    menuCli.detalheAdm(login, nome);
                    menuCli.setVisible(true);
                    menuCli.setAlwaysOnTop(true);
                    this.dispose();
                    menuCli.setAlwaysOnTop(false);
                }
            } else if (resp.equals("Administrador")) {
                try {
                    admRetorno = admControl.procurarAdm(senha);
                    if (admRetorno == null) {
                        JOptionPane.showMessageDialog(null,MensagemUtilUsuario.getValor(MensagemUtilUsuario.MSG_CAMPO_CERTO),MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO), JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (admRetorno.getUsuarioAdm().getSenha().equals(senha)) {
                    MenuAdm menuAdm = new MenuAdm();
                    menuAdm.setAdm(admRetorno);
                    String login = admRetorno.getUsuarioAdm().getLogin();
                    String nome = admRetorno.getNomeAdm();
                    menuAdm.detalheAdm(login, nome);
                    menuAdm.setVisible(true);
                    menuAdm.setAlwaysOnTop(true);
                    this.dispose();
                    menuAdm.setAlwaysOnTop(false);
                }
            } else if (resp.equals("SELECIONE")) {
                JOptionPane.showMessageDialog(null,MensagemUtilUsuario.getValor(MensagemUtilUsuario.MSG_ESCOLHA),MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_OBG), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbselecione;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel jllogin;
    private javax.swing.JLabel jlsenha;
    private javax.swing.JPasswordField pfsenha;
    private javax.swing.JTextField tflogin;
    // End of variables declaration//GEN-END:variables
public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Administrador getAdm() {
        return adm;
    }

    public void setAdm(Administrador adm) {
        this.adm = adm;
    }

    private void menuAdm(String login, String nome) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
