/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.construtora.view;

import br.com.construtora.controller.ImovelController;
import br.com.construtora.model.Endereco;
import br.com.construtora.model.Imovel;
import br.com.construtora.util.MensagemUtilImovel;
import br.com.construtora.util.MensagemUtilUsuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Lacerda
 */
public class CadastrarImovel extends javax.swing.JDialog {

    private Imovel imovel = new Imovel();
    private ImovelController imovelControl = new ImovelController();

    /**
     * Creates new form CadastrarImovel
     */
    public CadastrarImovel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbselecione = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taespecificacao = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfcep = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfnumero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfrua = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfbairro = new javax.swing.JTextField();
        cbcidade = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tacomplemento = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfcodigo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfpreco = new javax.swing.JTextField();
        tftamanho = new javax.swing.JTextField();
        cbuf = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SD Construtora - Cadastrar");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(810, 635));
        getContentPane().setLayout(null);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/casas.png"))); // NOI18N
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(670, 50, 120, 130);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Dados:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 120, 110, 15);

        jLabel2.setText("Tamanho: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 200, 110, 14);

        jLabel5.setText("Preço: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 250, 90, 14);

        jLabel4.setText("Andamento da obra: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 300, 150, 14);

        cbselecione.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "Inicial - Planejamento", "Construção", "Acabamento", "Final - Pronta" }));
        getContentPane().add(cbselecione);
        cbselecione.setBounds(160, 300, 127, 30);

        jLabel6.setText("Especificação: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 350, 140, 20);

        taespecificacao.setColumns(20);
        taespecificacao.setRows(5);
        jScrollPane1.setViewportView(taespecificacao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 350, 166, 80);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Endereço: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 120, 160, 15);

        jLabel8.setText("CEP: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 160, 60, 14);

        try {
            tfcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfcep);
        tfcep.setBounds(410, 150, 80, 30);

        jLabel9.setText("UF: ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(500, 160, 50, 14);

        jLabel10.setText("Nº: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(590, 160, 60, 14);
        getContentPane().add(tfnumero);
        tfnumero.setBounds(610, 150, 30, 30);

        jLabel11.setText("Cidade: ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(320, 200, 110, 14);

        jLabel12.setText("Rua: ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(320, 250, 100, 14);
        getContentPane().add(tfrua);
        tfrua.setBounds(410, 250, 230, 30);

        jLabel13.setText("Bairro: ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(320, 300, 120, 14);
        getContentPane().add(tfbairro);
        tfbairro.setBounds(410, 300, 160, 30);

        cbcidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "Pombal", "São Bentinho", "Cajazeirinhas", "São Domingos" }));
        getContentPane().add(cbcidade);
        cbcidade.setBounds(410, 200, 170, 30);

        jLabel14.setText("Complemento: ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(320, 350, 140, 14);

        tacomplemento.setColumns(20);
        tacomplemento.setRows(5);
        jScrollPane2.setViewportView(tacomplemento);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(410, 350, 190, 80);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 255, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/V.gif"))); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 530, 130, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/X.gif"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 530, 130, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CADASTRAR IMÓVEL");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(320, 10, 200, 17);

        jLabel3.setText("M²");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 210, 60, 14);

        jLabel17.setText("Código do Imóvel: ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(40, 160, 140, 14);
        getContentPane().add(tfcodigo);
        tfcodigo.setBounds(160, 150, 70, 30);

        jLabel18.setText("R$");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(140, 260, 60, 14);
        getContentPane().add(tfpreco);
        tfpreco.setBounds(160, 250, 70, 30);
        getContentPane().add(tftamanho);
        tftamanho.setBounds(160, 200, 70, 30);

        cbuf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "PB" }));
        getContentPane().add(cbuf);
        cbuf.setBounds(530, 150, 50, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cad.jpg"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, MensagemUtilUsuario.getValor(MensagemUtilUsuario.MSG_CANCEL), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_CANCEL), JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        imovel.setIdImovel((String) tfcodigo.getText());

        Double tamanho = Double.valueOf(tftamanho.getText());
        imovel.setPreco(tamanho);
        Double preco = Double.valueOf(tfpreco.getText());
        imovel.setPreco(preco);
        imovel.setEspecificacao(taespecificacao.getText());
        imovel.setAndamentoObra((String) cbselecione.getSelectedItem());

        Endereco endereco = new Endereco();
        endereco.setCep(tfcep.getText());
        endereco.setUf((String) cbuf.getSelectedItem());
        endereco.setNumero(tfnumero.getText());
        endereco.setCidade((String) cbcidade.getSelectedItem());
        endereco.setRua(tfrua.getText());
        endereco.setBairro(tfbairro.getText());
        endereco.setComplemento(tacomplemento.getText());
        imovel.setEnderecoImovel(endereco);

        try {
            int resp = JOptionPane.showConfirmDialog(null, MensagemUtilUsuario.getValor(MensagemUtilUsuario.MSG_CAD), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_CAD), JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                imovelControl.salvarImovel(imovel);
                JOptionPane.showMessageDialog(null, MensagemUtilImovel.getValor(MensagemUtilImovel.MSG_SUCESSO_SALVARIMO));
                dispose();
            }
        } catch (Exception ex) {
            Logger.getLogger(CadastrarImovel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, MensagemUtilImovel.getValor(MensagemUtilImovel.MSG_ERRO_SALVARIMO), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarImovel dialog = new CadastrarImovel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbcidade;
    private javax.swing.JComboBox cbselecione;
    private javax.swing.JComboBox cbuf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextArea tacomplemento;
    private javax.swing.JTextArea taespecificacao;
    private javax.swing.JTextField tfbairro;
    private javax.swing.JFormattedTextField tfcep;
    private javax.swing.JTextField tfcodigo;
    private javax.swing.JTextField tfnumero;
    private javax.swing.JTextField tfpreco;
    private javax.swing.JTextField tfrua;
    private javax.swing.JTextField tftamanho;
    // End of variables declaration//GEN-END:variables
}
