/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.construtora.view;

import br.com.construtora.controller.ImovelController;
import br.com.construtora.model.Endereco;
import br.com.construtora.model.Imovel;
import br.com.construtora.relatorio.ImovelRelatorio;
import br.com.construtora.util.ConfigFactoryUtil;
import br.com.construtora.util.MensagemUtilImovel;
import br.com.construtora.util.MensagemUtilUsuario;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Felipe Lacerda
 */
public class ImovelAll extends javax.swing.JDialog {

    private ImovelController imovelControl = new ImovelController();
    private DefaultTableModel modeloTableDados;
    private DefaultTableModel modeloTableEnde;

    /**
     * Creates new form AllImovel
     */
    public ImovelAll(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        listarImoveis(true);
        comboCidade(tbende, tbende.getColumnModel().getColumn(5));
        comboUf(tbende, tbende.getColumnModel().getColumn(8));
        comboAndamento(tbdados, tbdados.getColumnModel().getColumn(4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdados = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbende = new javax.swing.JTable();
        jbeditcli = new javax.swing.JButton();
        jbcadcli = new javax.swing.JToggleButton();
        jbexcli = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SD Construtora - Opções");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(812, 635));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OPÇÕES IMÓVEL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 10, 170, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Dados:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 50, 90, 15);

        tbdados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Imóvel:", "Tamanho:", "Preço:", "Especificação:", "Andamento:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbdados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 70, 800, 120);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Endereço:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 200, 120, 15);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("*Para EDITAR o dados dê DOIS cliques em sua linha!");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(250, 50, 330, 14);

        tbende.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Imóvel:", "ID End:", "Nº:", "Rua:", "Bairro:", "Cidade:", "CEP:", "Complemento:", "UF:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbende);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(0, 220, 800, 120);

        jbeditcli.setBackground(new java.awt.Color(255, 255, 255));
        jbeditcli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbeditcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/up.png"))); // NOI18N
        jbeditcli.setText(" Atualizar");
        jbeditcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeditcliActionPerformed(evt);
            }
        });
        getContentPane().add(jbeditcli);
        jbeditcli.setBounds(380, 340, 140, 40);

        jbcadcli.setBackground(new java.awt.Color(255, 255, 255));
        jbcadcli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbcadcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cont+.png"))); // NOI18N
        jbcadcli.setText("Cadastrar");
        jbcadcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcadcliActionPerformed(evt);
            }
        });
        getContentPane().add(jbcadcli);
        jbcadcli.setBounds(520, 340, 140, 40);

        jbexcli.setBackground(new java.awt.Color(255, 255, 255));
        jbexcli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbexcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lix2.png"))); // NOI18N
        jbexcli.setText(" Excluir");
        jbexcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexcliActionPerformed(evt);
            }
        });
        getContentPane().add(jbexcli);
        jbexcli.setBounds(660, 340, 140, 40);

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fe.png"))); // NOI18N
        jToggleButton1.setText("  Sair");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(340, 550, 130, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.jpg"))); // NOI18N
        jButton1.setText("Gerar Relatório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 340, 140, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cad.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbeditcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeditcliActionPerformed
        Imovel imo = editarImovel();
        try {
            imovelControl.atualizarImovel(imo);
            listarImoveis(true);
        } catch (Exception ex) {
            Logger.getLogger(ImovelAll.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbeditcliActionPerformed

    private void comboCidade(JTable tabela, TableColumn coluna) {
        String cidade[] = {"Pombal", "São Bentinho", "Cajazeirinhas", "São Domingos"};
        JComboBox combo = new JComboBox(cidade);
        coluna.setCellEditor(new DefaultCellEditor(combo));
    }

    private void comboUf(JTable tabela, TableColumn coluna) {
        String uf[] = {"PB", "PE", "CE", "RN"};
        JComboBox combo = new JComboBox(uf);
        coluna.setCellEditor(new DefaultCellEditor(combo));
    }

    private void comboAndamento(JTable tabela, TableColumn coluna) {
        String andamento[] = {"Inicial - Planejamento", "Construção", "Acabamento", "Final - Pronta"};
        JComboBox combo = new JComboBox(andamento);
        coluna.setCellEditor(new DefaultCellEditor(combo));
    }

    private void limparSelecao(JTable tableA) {
        tableA.clearSelection();
    }

    private Imovel editarImovel() {
        Imovel imo = new Imovel();
        Endereco ende = new Endereco();

        int linhaEnd = tbende.getSelectedRow();
        int linha = tbdados.getSelectedRow();

        int soma = (linha + linhaEnd);

        if (soma > -2) {
            if (linhaEnd > -1) {
                linha = linhaEnd;

                limparSelecao(tbdados);

                ende.setId((Long) tbende.getValueAt(linhaEnd, 1));
                ende.setNumero((String) tbende.getValueAt(linhaEnd, 2));
                ende.setRua((String) tbende.getValueAt(linhaEnd, 3));
                ende.setBairro((String) tbende.getValueAt(linhaEnd, 4));
                ende.setCidade((String) tbende.getValueAt(linhaEnd, 5));
                ende.setCep((String) tbende.getValueAt(linhaEnd, 6));
                ende.setComplemento((String) tbende.getValueAt(linhaEnd, 7));
                ende.setUf((String) tbende.getValueAt(linhaEnd, 8));
                imo.setEnderecoImovel(ende);

                imo.setIdImovel((String) tbdados.getValueAt(linha, 0));
                imo.setTamanho((Double) tbdados.getValueAt(linha, 1));
                imo.setPreco((Double) tbdados.getValueAt(linha, 2));
                imo.setEspecificacao((String) tbdados.getValueAt(linha, 3));
                imo.setAndamentoObra((String) tbdados.getValueAt(linha, 4));

            }

            if (linha > -1) {
                linhaEnd = linha;

                limparSelecao(tbende);

                ende.setId((Long) tbende.getValueAt(linhaEnd, 1));
                ende.setNumero((String) tbende.getValueAt(linhaEnd, 2));
                ende.setRua((String) tbende.getValueAt(linhaEnd, 3));
                ende.setBairro((String) tbende.getValueAt(linhaEnd, 4));
                ende.setCidade((String) tbende.getValueAt(linhaEnd, 5));
                ende.setCep((String) tbende.getValueAt(linhaEnd, 6));
                ende.setComplemento((String) tbende.getValueAt(linhaEnd, 7));
                ende.setUf((String) tbende.getValueAt(linhaEnd, 8));
                imo.setEnderecoImovel(ende);

                imo.setIdImovel((String) tbdados.getValueAt(linha, 0));
                imo.setTamanho((Double) tbdados.getValueAt(linha, 1));
                imo.setPreco((Double) tbdados.getValueAt(linha, 2));
                imo.setEspecificacao((String) tbdados.getValueAt(linha, 3));
                imo.setAndamentoObra((String) tbdados.getValueAt(linha, 4));

            }
        } else {
            JOptionPane.showMessageDialog(null, ConfigFactoryUtil.getValor(ConfigFactoryUtil.ERROLINHA),
                    MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO),
                    JOptionPane.ERROR_MESSAGE);
        }
        return imo;
    }

    private void jbcadcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcadcliActionPerformed
        CadastrarImovel cadImovel = new CadastrarImovel(null, true);
        cadImovel.setVisible(true);
        listarImoveis(true);
    }//GEN-LAST:event_jbcadcliActionPerformed

    private void jbexcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexcliActionPerformed
        Imovel imo = editarImovel();
        int resposta = JOptionPane.showConfirmDialog(null, MensagemUtilUsuario.getValor(MensagemUtilUsuario.MSG_REM), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_REM), JOptionPane.YES_NO_OPTION);
        if (resposta == 0) {
            try {
                imovelControl.removerImovel(imo);
                listarImoveis(true);
            } catch (Exception ex) {
                Logger.getLogger(ClienteAll.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbexcliActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Imovel> imoveis = new ArrayList<Imovel>();
        try {
            imoveis = imovelControl.listarImoveis();
        } catch (Exception ex) {
            Logger.getLogger(ImovelAll.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImovelRelatorio imoRel = new ImovelRelatorio();
        try {
            imoRel.imprimirRelatorio(imoveis);
        } catch (JRException ex) {
            Logger.getLogger(ImovelAll.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void listarImoveis(Boolean resposta) {
        modeloTableDados = (DefaultTableModel) tbdados.getModel();
        modeloTableEnde = (DefaultTableModel) tbende.getModel();

        if (resposta == true) {
            List<Imovel> imoveis = new ArrayList<Imovel>();
            try {
                imoveis = imovelControl.listarImoveis();
            } catch (Exception ex) {
                Logger.getLogger(Listar.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, MensagemUtilImovel.getValor(MensagemUtilImovel.MSG_ERRO_LISTARIMO), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_ERRO), JOptionPane.ERROR_MESSAGE);

            }
            if (imoveis == null) {
                JOptionPane.showMessageDialog(null, MensagemUtilImovel.getValor(MensagemUtilImovel.MSG_ERRO_LISTARIMO), MensagemUtilUsuario.getValor(MensagemUtilUsuario.CABE_OBG), JOptionPane.ERROR_MESSAGE);
            } else {

                while (modeloTableDados.getRowCount() > 0) {
                    modeloTableDados.removeRow(0);
                }

                for (Imovel i : imoveis) {
                    modeloTableDados.addRow(new Object[]{
                        i.getIdImovel(), i.getTamanho(),
                        i.getPreco(), i.getEspecificacao(),
                        i.getAndamentoObra()});
                }

                while (modeloTableEnde.getRowCount() > 0) {
                    modeloTableEnde.removeRow(0);
                }

                for (Imovel i : imoveis) {
                    modeloTableEnde.addRow(new Object[]{
                        i.getIdImovel(), i.getEnderecoImovel().getId(), i.getEnderecoImovel().getNumero(),
                        i.getEnderecoImovel().getRua(), i.getEnderecoImovel().getBairro(), i.getEnderecoImovel().getCidade(),
                        i.getEnderecoImovel().getCep(), i.getEnderecoImovel().getComplemento(), i.getEnderecoImovel().getUf()
                    });
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImovelAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImovelAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImovelAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImovelAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImovelAll dialog = new ImovelAll(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jbcadcli;
    private javax.swing.JButton jbeditcli;
    private javax.swing.JToggleButton jbexcli;
    private javax.swing.JTable tbdados;
    private javax.swing.JTable tbende;
    // End of variables declaration//GEN-END:variables
}
